easy_admin:
    design:
      menu: 
        - label: 'School management'
          icon: 'newspaper-o'
          children: 
            - {entity: 'Subject', icon: 'folder-open', label: 'Matières'}
            - {entity: 'Planning', icon: 'folder-open', label: 'Planning'}
            - {entity: 'News', icon: 'folder-open', label: 'Actualitées'}