easy_admin:
  entities:
    Planning:
      class: App\Entity\Planning
      form: 
        fields: 
          - {property: 'date'}
          - {property: 'userId'}
          - {property: 'classId'}
          - {property: 'subjectId'}


      list:
        fields:
          - {property: 'date'}
          - {property: 'userId'}
          - {property: 'classId'}
          - {property: 'subjectId'}