easy_admin:
  entities:
    Profil:
      class: App\Entity\Profil
      form: 
        fields: 
          - {property: 'firstName'}
          - {property: 'lastName'}
          - {property: 'birthdate'}
          - {property: 'function'}
          - {property: 'userId'}


      list:
        fields:
          - {property: 'firstName', label: 'Nom'}
          - {property: 'lastName', label: 'Prènom'}
          - {property: 'birthdate', label: 'Date de naissance'}
          - {property: 'function', label: 'Fonction'}
          - {property: 'userId', label: 'utilisateur'}