easy_admin:
  entities:
    User:
        class: App\Entity\User
        form: 
          fields: 
            - {property: 'username'}
            - {property: 'password'}            
            - {property: 'Roles', type: 'collection'}
            - {property: 'firstName'}
            - {property: 'lastName'}
            - {property: 'birthdate'}
            - {property: 'function'}
        
        list:
          fields:
            - {property: 'firstName', label: 'Nom'}
            - {property: 'lastName', label: 'Prènom'}
            - {property: 'birthdate', label: 'Date de naissance'}
            - {property: 'function', label: 'Fonction'}
          actions:
            - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-primary'}
            - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}